In [1]:
import numpy as np

In [2]:
letras = 'abcdefghijklmnopqrstuvwxyz@#*+'


In [3]:
lista = list(letras)
print('len(lista):', len(lista))
print(lista)


len(lista): 30
['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '@', '#', '*', '+']


In [4]:
lista = np.array(lista)

In [5]:
print('tamanho:', len(lista))
print('shape:', lista.shape)
print('ndim:', lista.ndim)
print('lista:', lista)
print('lista-reverso:', lista[::-1])

tamanho: 30
shape: (30,)
ndim: 1
lista: ['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k' 'l' 'm' 'n' 'o' 'p' 'q' 'r'
 's' 't' 'u' 'v' 'w' 'x' 'y' 'z' '@' '#' '*' '+']
lista-reverso: ['+' '*' '#' '@' 'z' 'y' 'x' 'w' 'v' 'u' 't' 's' 'r' 'q' 'p' 'o' 'n' 'm'
 'l' 'k' 'j' 'i' 'h' 'g' 'f' 'e' 'd' 'c' 'b' 'a']


In [6]:
print ('primeiros 10 elementos:', lista[:10])
print ('ultimos 10 elementos:', lista[-10:])
print ('21° elemento:', lista[20])
print ('imprimir todos, menos os 5 ultimos:', lista[:-5])
print ('imprimir todos os lementos do inicio até o meio:', lista[:len(lista)//2])
print ('imprimir todos os elementos do meio até o final:', lista[len(lista)//2:])
print ('imprimir todos os elementos do meio até o final, em ordem reversa:', lista[:len(lista)//2:-1])
print ('imprimir todos os elementos a partir do 5, menos os 5 ultimos:', lista[5:-5])
print ('imprimir o 12° elemento:', lista[11])



primeiros 10 elementos: ['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j']
ultimos 10 elementos: ['u' 'v' 'w' 'x' 'y' 'z' '@' '#' '*' '+']
21° elemento: u
imprimir todos, menos os 5 ultimos: ['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k' 'l' 'm' 'n' 'o' 'p' 'q' 'r'
 's' 't' 'u' 'v' 'w' 'x' 'y']
imprimir todos os lementos do inicio até o meio: ['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k' 'l' 'm' 'n' 'o']
imprimir todos os elementos do meio até o final: ['p' 'q' 'r' 's' 't' 'u' 'v' 'w' 'x' 'y' 'z' '@' '#' '*' '+']
imprimir todos os elementos do meio até o final, em ordem reversa: ['+' '*' '#' '@' 'z' 'y' 'x' 'w' 'v' 'u' 't' 's' 'r' 'q']
imprimir todos os elementos a partir do 5, menos os 5 ultimos: ['f' 'g' 'h' 'i' 'j' 'k' 'l' 'm' 'n' 'o' 'p' 'q' 'r' 's' 't' 'u' 'v' 'w'
 'x' 'y']
imprimir o 12° elemento: l


In [7]:
for i in range(0, len(lista), 3):
    print('i:', i)
    print('lista:', lista[:i])
    print('---')


i: 0
lista: []
---
i: 3
lista: ['a' 'b' 'c']
---
i: 6
lista: ['a' 'b' 'c' 'd' 'e' 'f']
---
i: 9
lista: ['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i']
---
i: 12
lista: ['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k' 'l']
---
i: 15
lista: ['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k' 'l' 'm' 'n' 'o']
---
i: 18
lista: ['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k' 'l' 'm' 'n' 'o' 'p' 'q' 'r']
---
i: 21
lista: ['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k' 'l' 'm' 'n' 'o' 'p' 'q' 'r'
 's' 't' 'u']
---
i: 24
lista: ['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k' 'l' 'm' 'n' 'o' 'p' 'q' 'r'
 's' 't' 'u' 'v' 'w' 'x']
---
i: 27
lista: ['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k' 'l' 'm' 'n' 'o' 'p' 'q' 'r'
 's' 't' 'u' 'v' 'w' 'x' 'y' 'z' '@']
---


In [8]:

for idx in range(10):
    ii = idx * 3
    print(lista[ii:ii+3])
    print('indice:', ii)
    print('---')


['a' 'b' 'c']
indice: 0
---
['d' 'e' 'f']
indice: 3
---
['g' 'h' 'i']
indice: 6
---
['j' 'k' 'l']
indice: 9
---
['m' 'n' 'o']
indice: 12
---
['p' 'q' 'r']
indice: 15
---
['s' 't' 'u']
indice: 18
---
['v' 'w' 'x']
indice: 21
---
['y' 'z' '@']
indice: 24
---
['#' '*' '+']
indice: 27
---


In [9]:
TAB = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
]
print(TAB)
TAB = np.array(TAB)
print(TAB)

print('ndim -->', TAB.ndim)

print('MOSTRANDO INDICE -->',TAB[1,1])

print('ultima lista -->', TAB[-1])

print('tabela invertida -->', TAB[::-1])

print('coluna meio -->', TAB[:, 1])

diag = np.diag(TAB)
print('diagonal -->', diag)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim --> 2
MOSTRANDO INDICE --> 5
ultima lista --> [7 8 9]
tabela invertida --> [[7 8 9]
 [4 5 6]
 [1 2 3]]
coluna meio --> [2 5 8]
diagonal --> [1 5 9]


In [10]:
# https://numpy.org/doc/2.2/reference/generated/numpy.transpose.html

tabela = np.matrix([['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'],
                     ['k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't'],
                     ['u', 'v', 'w', 'x', 'y', 'z', '@', '#', '*', '+']])   

tabela_t = np.transpose(tabela)
print ('Tabela\n', tabela)
print ('Tabela Transposta\n', tabela_t)

Tabela
 [['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j']
 ['k' 'l' 'm' 'n' 'o' 'p' 'q' 'r' 's' 't']
 ['u' 'v' 'w' 'x' 'y' 'z' '@' '#' '*' '+']]
Tabela Transposta
 [['a' 'k' 'u']
 ['b' 'l' 'v']
 ['c' 'm' 'w']
 ['d' 'n' 'x']
 ['e' 'o' 'y']
 ['f' 'p' 'z']
 ['g' 'q' '@']
 ['h' 'r' '#']
 ['i' 's' '*']
 ['j' 't' '+']]
